# /etc/mosdns/config.yaml
log:
  level: info

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400

  # 转发至本地服务器 DNSPod aliyun
  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: https://1.12.12.12/dns-query
        - addr: https://223.5.5.5/dns-query
        - addr: https://223.6.6.6/dns-query

  # 转发至远程服务器 google
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: https://8.8.4.4/dns-query
        - addr: tls://8.8.8.8:853

  # fallback 用本地服务器 sequence
  # 返回不包含本地 ip 则 reject
  - tag: local_ip_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip &/etc/mosdns/CN-ip-cidr.txt
        exec: accept
      - exec: drop_resp # v5.1.2 以后不能用 reject

  # fallback 用远程服务器 sequence
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - exec: accept

  # fallback 用远程服务器 sequence
  - tag: "fallback"
    type: "fallback"
    args:
      primary: local_ip_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - exec: $cache
      - matches: has_resp
        exec: accept
      - matches: qname &/etc/mosdns/direct-list.txt &/etc/mosdns/apple-cn.txt &/etc/mosdns/force-cn.txt
        exec: $forward_local 
      - matches: has_resp
        exec: accept
      - exec: $fallback

  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: 0.0.0.0:53
