
version: '3'

services:
    mosdns:
        image: irinesistiana/mosdns
        container_name: mosdns
        restart: unless-stopped
        ports:
          - "553:53/udp"
        volumes:
          - /etc/mosdns/:/etc/mosdns/
